# Base de Datos
# Diccionario de Intervalos por Nota
Intervalos = {
    "Cbb": {
        "I Justa": "Cbb",
        "I Aumentada": "Cb",
        "II Disminuida": "None",
        "II Menor": "None",
        "II Mayor": "Dbb",
        "II Aumentada": "Db",
        "III Disminuida": "None",
        "III Menor": "None",
        "III Mayor": "Ebb",
        "III Aumentada": "Eb",
        "IV Disminuida": "None",
        "IV Justa": "Fbb",
        "IV Aumentada": "Fb",
        "V Disminuida": "None",
        "V Justa": "Gbb",
        "V Aumentada": "Gb",
        "VI Disminuida": "None",
        "VI Menor": "None",
        "VI Mayor": "Abb",
        "VI Aumentada": "Ab",
        "VII Disminuida": "None",
        "VII Menor": "None",
        "VII Mayor": "Bbb",
        "VII Aumentada":"Bb"
    },
    "Cb": {
        "I Justa": "Cb",
        "I Aumentada": "C",
        "II Disminuida": "None",
        "II Menor": "Dbb",
        "II Mayor": "Db",
        "II Aumentada": "D",
        "III Disminuida": "None",
        "III Menor": "Ebb",
        "III Mayor": "Eb",
        "III Aumentada": "E",
        "IV Disminuida": "Fbb",
        "IV Justa": "Fb",
        "IV Aumentada": "F",
        "V Disminuida": "Gbb",
        "V Justa": "Gb",
        "V Aumentada": "G",
        "VI Disminuida": "None",
        "VI Menor": "Abb",
        "VI Mayor": "Ab",
        "VI Aumentada": "A",
        "VII Disminuida": "None",
        "VII Menor": "Bbb",
        "VII Mayor": "Bb",
        "VII Aumentada":"B"
    },
    "C": {
        "I Justa": "C",
        "I Aumentada": "C#",
        "II Disminuida": "Dbb",
        "II Menor": "Db",
        "II Mayor": "D",
        "II Aumentada": "D#",
        "III Disminuida": "Ebb",
        "III Menor": "Eb",
        "III Mayor": "E",
        "III Aumentada": "E#",
        "IV Disminuida": "Fb",
        "IV Justa": "F",
        "IV Aumentada": "F#",
        "V Disminuida": "Gb",
        "V Justa": "G",
        "V Aumentada": "G#",
        "VI Disminuida": "Abb",
        "VI Menor": "Ab",
        "VI Mayor": "A",
        "VI Aumentada": "A#",
        "VII Disminuida": "Bbb",
        "VII Menor": "Bb",
        "VII Mayor": "B",
        "VII Aumentada":"B#"
    },
    "C#": {
        "I Justa": "C#",
        "I Aumentada": "Cx",
        "II Disminuida": "Db",
        "II Menor": "D",
        "II Mayor": "D#",
        "II Aumentada": "Dx",
        "III Disminuida": "Eb",
        "III Menor": "E",
        "III Mayor": "E#",
        "III Aumentada": "Ex",
        "IV Disminuida": "F",
        "IV Justa": "F#",
        "IV Aumentada": "Fx",
        "V Disminuida": "G",
        "V Justa": "G#",
        "V Aumentada": "Gx",
        "VI Disminuida": "Ab",
        "VI Menor": "A",
        "VI Mayor": "A#",
        "VI Aumentada": "Ax",
        "VII Disminuida": "Bb",
        "VII Menor": "B",
        "VII Mayor": "B#",
        "VII Aumentada":"Bx"
    },
    "Cx": {
        "I Justa": "Cx",
        "I Aumentada": "None",
        "II Disminuida": "D",
        "II Menor": "D#",
        "II Mayor": "Dx",
        "II Aumentada": "None",
        "III Disminuida": "E",
        "III Menor": "E#",
        "III Mayor": "Ex",
        "III Aumentada": "None",
        "IV Disminuida": "F#",
        "IV Justa": "Fx",
        "IV Aumentada": "X",
        "V Disminuida": "G#",
        "V Justa": "Gx",
        "V Aumentada": "None",
        "VI Disminuida": "A",
        "VI Menor": "A#",
        "VI Mayor": "Ax",
        "VI Aumentada": "None",
        "VII Disminuida": "B",
        "VII Menor": "B#",
        "VII Mayor": "Bx",
        "VII Aumentada":"None"
    },
    "Dbb": {
        "I Justa": "Dbb",
        "I Aumentada": "Db",
        "II Disminuida": "None",
        "II Menor": "None",
        "II Mayor": "Ebb",
        "II Aumentada": "Eb",
        "III Disminuida": "None",
        "III Menor": "Fbb",
        "III Mayor": "Fb",
        "III Aumentada": "F",
        "IV Disminuida": "None",
        "IV Justa": "Gbb",
        "IV Aumentada": "Gb",
        "V Disminuida": "None",
        "V Justa": "Abb",
        "V Aumentada": "Ab",
        "VI Disminuida": "None",
        "VI Menor": "None",
        "VI Mayor": "Bbb",
        "VI Aumentada": "Bb",
        "VII Disminuida": "None",
        "VII Menor": "Cbb",
        "VII Mayor": "Cb",
        "VII Aumentada":"C"
    },
    "Db": {
        "I Justa": "Db",
        "I Aumentada": "D",
        "II Disminuida": "None",
        "II Menor": "Ebb",
        "II Mayor": "Eb",
        "II Aumentada": "E",
        "III Disminuida": "Fbb",
        "III Menor": "Fb",
        "III Mayor": "F",
        "III Aumentada": "F#",
        "IV Disminuida": "Gbb",
        "IV Justa": "Gb",
        "IV Aumentada": "G",
        "V Disminuida": "Abb",
        "V Justa": "Ab",
        "V Aumentada": "A",
        "VI Disminuida": "None",
        "VI Menor": "Bbb",
        "VI Mayor": "Bb",
        "VI Aumentada": "B",
        "VII Disminuida": "Cbb",
        "VII Menor": "Cb",
        "VII Mayor": "C",
        "VII Aumentada":"C#"
    },
    "D": {
        "I Justa": "D",
        "I Aumentada": "D#",
        "II Disminuida": "Ebb",
        "II Menor": "Eb",
        "II Mayor": "E",
        "II Aumentada": "E#",
        "III Disminuida": "Fb",
        "III Menor": "F",
        "III Mayor": "F#",
        "III Aumentada": "Fx",
        "IV Disminuida": "Gb",
        "IV Justa": "G",
        "IV Aumentada": "G#",
        "V Disminuida": "Ab",
        "V Justa": "A",
        "V Aumentada": "A#",
        "VI Disminuida": "Bbb",
        "VI Menor": "Bb",
        "VI Mayor": "B",
        "VI Aumentada": "B#",
        "VII Disminuida": "Cb",
        "VII Menor": "C",
        "VII Mayor": "C#",
        "VII Aumentada":"Cx"
    },
    "D#": {
        "I Justa": "D#",
        "I Aumentada": "Dx",
        "II Disminuida": "Eb",
        "II Menor": "E",
        "II Mayor": "E#",
        "II Aumentada": "Ex",
        "III Disminuida": "F",
        "III Menor": "F#",
        "III Mayor": "Fx",
        "III Aumentada": "None",
        "IV Disminuida": "G",
        "IV Justa": "G#",
        "IV Aumentada": "Gx",
        "V Disminuida": "A",
        "V Justa": "A#",
        "V Aumentada": "Ax",
        "VI Disminuida": "Bb",
        "VI Menor": "B",
        "VI Mayor": "B#",
        "VI Aumentada": "Bx",
        "VII Disminuida": "C",
        "VII Menor": "C#",
        "VII Mayor": "Cx",
        "VII Aumentada":"None"
    },
    "Dx": {
        "I Justa": "Dx",
        "I Aumentada": "None",
        "II Disminuida": "E",
        "II Menor": "E#",
        "II Mayor": "Ex",
        "II Aumentada": "None",
        "III Disminuida": "F#",
        "III Menor": "Fx",
        "III Mayor": "None",
        "III Aumentada": "None",
        "IV Disminuida": "G#",
        "IV Justa": "Gx",
        "IV Aumentada": "None",
        "V Disminuida": "A#",
        "V Justa": "Ax",
        "V Aumentada": "None",
        "VI Disminuida": "B",
        "VI Menor": "B#",
        "VI Mayor": "Bx",
        "VI Aumentada": "None",
        "VII Disminuida": "C#",
        "VII Menor": "Cx",
        "VII Mayor": "None",
        "VII Aumentada":"None"
    },
    "Ebb": {
        "I Justa": "Ebb",
        "I Aumentada": "Eb",
        "II Disminuida": "None",
        "II Menor": "Fbb",
        "II Mayor": "Fb",
        "II Aumentada": "F",
        "III Disminuida": "None",
        "III Menor": "Gbb",
        "III Mayor": "Gb",
        "III Aumentada": "G",
        "IV Disminuida": "None",
        "IV Justa": "Abb",
        "IV Aumentada": "Ab",
        "V Disminuida": "None",
        "V Justa": "Bbb",
        "V Aumentada": "Bb",
        "VI Disminuida": "None",
        "VI Menor": "Cbb",
        "VI Mayor": "Cb",
        "VI Aumentada": "C",
        "VII Disminuida": "None",
        "VII Menor": "Dbb",
        "VII Mayor": "Db",
        "VII Aumentada":"D"
    },
    "Eb": {
        "I Justa": "Eb",
        "I Aumentada": "E",
        "II Disminuida": "Fbb",
        "II Menor": "Fb",
        "II Mayor": "F",
        "II Aumentada": "F#",
        "III Disminuida": "Gbb",
        "III Menor": "Gb",
        "III Mayor": "G",
        "III Aumentada": "G#",
        "IV Disminuida": "Abb",
        "IV Justa": "Ab",
        "IV Aumentada": "A",
        "V Disminuida": "Bbb",
        "V Justa": "Bb",
        "V Aumentada": "B",
        "VI Disminuida": "Cbb",
        "VI Menor": "Cb",
        "VI Mayor": "C",
        "VI Aumentada": "C#",
        "VII Disminuida": "Dbb",
        "VII Menor": "Db",
        "VII Mayor": "D",
        "VII Aumentada":"D#"
    },
    "E": {
        "I Justa": "E",
        "I Aumentada": "E#",
        "II Disminuida": "Fb",
        "II Menor": "F",
        "II Mayor": "F#",
        "II Aumentada": "Fx",
        "III Disminuida": "Gb",
        "III Menor": "G",
        "III Mayor": "G#",
        "III Aumentada": "Gx",
        "IV Disminuida": "Ab",
        "IV Justa": "A",
        "IV Aumentada": "A#",
        "V Disminuida": "Bb",
        "V Justa": "B",
        "V Aumentada": "B#",
        "VI Disminuida": "Cb",
        "VI Menor": "C",
        "VI Mayor": "C#",
        "VI Aumentada": "Cx",
        "VII Disminuida": "Db",
        "VII Menor": "D",
        "VII Mayor": "D#",
        "VII Aumentada":"Dx"
    },
    "E#": {
        "I Justa": "E#",
        "I Aumentada": "Ex",
        "II Disminuida": "F",
        "II Menor": "F#",
        "II Mayor": "Fx",
        "II Aumentada": "None",
        "III Disminuida": "G",
        "III Menor": "G#",
        "III Mayor": "Gx",
        "III Aumentada": "None",
        "IV Disminuida": "A",
        "IV Justa": "A#",
        "IV Aumentada": "Ax",
        "V Disminuida": "B",
        "V Justa": "B#",
        "V Aumentada": "Bx",
        "VI Disminuida": "C",
        "VI Menor": "C#",
        "VI Mayor": "Cx",
        "VI Aumentada": "None",
        "VII Disminuida": "D",
        "VII Menor": "D#",
        "VII Mayor": "Dx",
        "VII Aumentada":"None"
    },
    "Ex": {
        "I Justa": "Ex",
        "I Aumentada": "None",
        "II Disminuida": "F#",
        "II Menor": "Fx",
        "II Mayor": "None",
        "II Aumentada": "None",
        "III Disminuida": "G#",
        "III Menor": "Gx",
        "III Mayor": "None",
        "III Aumentada": "None",
        "IV Disminuida": "A#",
        "IV Justa": "Ax",
        "IV Aumentada": "None",
        "V Disminuida": "B#",
        "V Justa": "Bx",
        "V Aumentada": "None",
        "VI Disminuida": "C#",
        "VI Menor": "Cx",
        "VI Mayor": "None",
        "VI Aumentada": "None",
        "VII Disminuida": "D#",
        "VII Menor": "Dx",
        "VII Mayor": "None",
        "VII Aumentada":"None"
    },
    "Fbb": {
        "I Justa": "Fbb",
        "I Aumentada": "Fb",
        "II Disminuida": "None",
        "II Menor": "None",
        "II Mayor": "Gbb",
        "II Aumentada": "Gb",
        "III Disminuida": "None",
        "III Menor": "None",
        "III Mayor": "Abb",
        "III Aumentada": "Ab",
        "IV Disminuida": "None",
        "IV Justa": "None",
        "IV Aumentada": "Bbb",
        "V Disminuida": "None",
        "V Justa": "Cbb",
        "V Aumentada": "Cb",
        "VI Disminuida": "None",
        "VI Menor": "None",
        "VI Mayor": "Dbb",
        "VI Aumentada": "Db",
        "VII Disminuida": "None",
        "VII Menor": "None",
        "VII Mayor": "Ebb",
        "VII Aumentada":"Eb"
    },
    "Fb": {
        "I Justa": "Fb",
        "I Aumentada": "F",
        "II Disminuida": "None",
        "II Menor": "Gbb",
        "II Mayor": "Gb",
        "II Aumentada": "G",
        "III Disminuida": "None",
        "III Menor": "Abb",
        "III Mayor": "Ab",
        "III Aumentada": "A",
        "IV Disminuida": "None",
        "IV Justa": "Bbb",
        "IV Aumentada": "Bb",
        "V Disminuida": "Cbb",
        "V Justa": "Cb",
        "V Aumentada": "C",
        "VI Disminuida": "None",
        "VI Menor": "Dbb",
        "VI Mayor": "Db",
        "VI Aumentada": "D",
        "VII Disminuida": "None",
        "VII Menor": "Ebb",
        "VII Mayor": "Eb",
        "VII Aumentada":"E"
    },
    "F": {
        "I Justa": "F",
        "I Aumentada": "F#",
        "II Disminuida": "Gbb",
        "II Menor": "Gb",
        "II Mayor": "G",
        "II Aumentada": "G#",
        "III Disminuida": "Abb",
        "III Menor": "Ab",
        "III Mayor": "A",
        "III Aumentada": "A#",
        "IV Disminuida": "Bbb",
        "IV Justa": "Bb",
        "IV Aumentada": "B",
        "V Disminuida": "Cb",
        "V Justa": "C",
        "V Aumentada": "C#",
        "VI Disminuida": "Dbb",
        "VI Menor": "Db",
        "VI Mayor": "D",
        "VI Aumentada": "D#",
        "VII Disminuida": "Ebb",
        "VII Menor": "Eb",
        "VII Mayor": "E",
        "VII Aumentada":"E#"
    },
    "F#": {
        "I Justa": "F#",
        "I Aumentada": "Fx",
        "II Disminuida": "Gb",
        "II Menor": "G",
        "II Mayor": "G#",
        "II Aumentada": "Gx",
        "III Disminuida": "Ab",
        "III Menor": "A",
        "III Mayor": "A#",
        "III Aumentada": "Ax",
        "IV Disminuida": "Bb",
        "IV Justa": "B",
        "IV Aumentada": "B#",
        "V Disminuida": "C",
        "V Justa": "C#",
        "V Aumentada": "Cx",
        "VI Disminuida": "Db",
        "VI Menor": "D",
        "VI Mayor": "D#",
        "VI Aumentada": "Dx",
        "VII Disminuida": "Eb",
        "VII Menor": "E",
        "VII Mayor": "E#",
        "VII Aumentada":"Ex"
    },
    "Fx": {
        "I Justa": "Fx",
        "I Aumentada": "Fx",
        "II Disminuida": "G",
        "II Menor": "G#",
        "II Mayor": "Gx",
        "II Aumentada": "None",
        "III Disminuida": "A",
        "III Menor": "A#",
        "III Mayor": "Ax",
        "III Aumentada": "None",
        "IV Disminuida": "B",
        "IV Justa": "B#",
        "IV Aumentada": "Bx",
        "V Disminuida": "C#",
        "V Justa": "Cx",
        "V Aumentada": "None",
        "VI Disminuida": "D",
        "VI Menor": "D#",
        "VI Mayor": "Dx",
        "VI Aumentada": "None",
        "VII Disminuida": "E",
        "VII Menor": "E#",
        "VII Mayor": "Ex",
        "VII Aumentada":"None"
    },
    "Gbb": {
        "I Justa": "Gbb",
        "I Aumentada": "Gb",
        "II Disminuida": "None",
        "II Menor": "None",
        "II Mayor": "Abb",
        "II Aumentada": "Ab",
        "III Disminuida": "None",
        "III Menor": "None",
        "III Mayor": "Bbb",
        "III Aumentada": "Bb",
        "IV Disminuida": "None",
        "IV Justa": "Cbb",
        "IV Aumentada": "Cb",
        "V Disminuida": "None",
        "V Justa": "Dbb",
        "V Aumentada": "Db",
        "VI Disminuida": "None",
        "VI Menor": "None",
        "VI Mayor": "Ebb",
        "VI Aumentada": "Eb",
        "VII Disminuida": "None",
        "VII Menor": "Fbb",
        "VII Mayor": "Fb",
        "VII Aumentada":"F"
    },
    "Gb": {
        "I Justa": "Gb",
        "I Aumentada": "G",
        "II Disminuida": "None",
        "II Menor": "Abb",
        "II Mayor": "Ab",
        "II Aumentada": "A",
        "III Disminuida": "None",
        "III Menor": "Bbb",
        "III Mayor": "Bb",
        "III Aumentada": "B",
        "IV Disminuida": "Cbb",
        "IV Justa": "Cb",
        "IV Aumentada": "C",
        "V Disminuida": "Dbb",
        "V Justa": "Db",
        "V Aumentada": "D",
        "VI Disminuida": "None",
        "VI Menor": "Ebb",
        "VI Mayor": "Eb",
        "VI Aumentada": "E",
        "VII Disminuida": "Fbb",
        "VII Menor": "Fb",
        "VII Mayor": "F",
        "VII Aumentada":"F#"
    },
    "G": {
        "I Justa": "G",
        "I Aumentada": "G#",
        "II Disminuida": "Abb",
        "II Menor": "Ab",
        "II Mayor": "A",
        "II Aumentada": "A#",
        "III Disminuida": "Bbb",
        "III Menor": "Bb",
        "III Mayor": "B",
        "III Aumentada": "B#",
        "IV Disminuida": "Cb",
        "IV Justa": "C",
        "IV Aumentada": "C#",
        "V Disminuida": "Db",
        "V Justa": "D",
        "V Aumentada": "D#",
        "VI Disminuida": "Ebb",
        "VI Menor": "Eb",
        "VI Mayor": "E",
        "VI Aumentada": "E#",
        "VII Disminuida": "Fb",
        "VII Menor": "F",
        "VII Mayor": "F#",
        "VII Aumentada":"Fx"
    },
    "G#": {
        "I Justa": "G#",
        "I Aumentada": "Gx",
        "II Disminuida": "Ab",
        "II Menor": "A",
        "II Mayor": "A#",
        "II Aumentada": "Ax",
        "III Disminuida": "Bb",
        "III Menor": "B",
        "III Mayor": "B#",
        "III Aumentada": "Bx",
        "IV Disminuida": "C",
        "IV Justa": "C#",
        "IV Aumentada": "Cx",
        "V Disminuida": "D",
        "V Justa": "D#",
        "V Aumentada": "Dx",
        "VI Disminuida": "Eb",
        "VI Menor": "E",
        "VI Mayor": "E#",
        "VI Aumentada": "Ex",
        "VII Disminuida": "F",
        "VII Menor": "F#",
        "VII Mayor": "Fx",
        "VII Aumentada":"None"
    },
    "Gx": {
        "I Justa": "Gx",
        "I Aumentada": "None",
        "II Disminuida": "A",
        "II Menor": "A#",
        "II Mayor": "Ax",
        "II Aumentada": "None",
        "III Disminuida": "B",
        "III Menor": "B#",
        "III Mayor": "Bx",
        "III Aumentada": "None",
        "IV Disminuida": "C#",
        "IV Justa": "Cx",
        "IV Aumentada": "None",
        "V Disminuida": "D#",
        "V Justa": "Dx",
        "V Aumentada": "None",
        "VI Disminuida": "E",
        "VI Menor": "E#",
        "VI Mayor": "Ex",
        "VI Aumentada": "None",
        "VII Disminuida": "F#",
        "VII Menor": "Fx",
        "VII Mayor": "None",
        "VII Aumentada":"None"
    },
    "Abb": {
        "I Justa": "Abb",
        "I Aumentada": "Ab",
        "II Disminuida": "None",
        "II Menor": "None",
        "II Mayor": "Bbb",
        "II Aumentada": "Bb",
        "III Disminuida": "None",
        "III Menor": "Cbb",
        "III Mayor": "Cb",
        "III Aumentada": "C",
        "IV Disminuida": "None",
        "IV Justa": "Dbb",
        "IV Aumentada": "Db",
        "V Disminuida": "None",
        "V Justa": "Ebb",
        "V Aumentada": "Eb",
        "VI Disminuida": "None",
        "VI Menor": "Fbb",
        "VI Mayor": "Fb",
        "VI Aumentada": "F",
        "VII Disminuida": "None",
        "VII Menor": "Gbb",
        "VII Mayor": "Gb",
        "VII Aumentada":"G"
    },
    "Ab": {
        "I Justa": "Ab",
        "I Aumentada": "A",
        "II Disminuida": "None",
        "II Menor": "Bbb",
        "II Mayor": "Bb",
        "II Aumentada": "B",
        "III Disminuida": "Cbb",
        "III Menor": "Cb",
        "III Mayor": "C",
        "III Aumentada": "C#",
        "IV Disminuida": "Dbb",
        "IV Justa": "Db",
        "IV Aumentada": "D",
        "V Disminuida": "Ebb",
        "V Justa": "Eb",
        "V Aumentada": "E",
        "VI Disminuida": "Fbb",
        "VI Menor": "Fb",
        "VI Mayor": "F",
        "VI Aumentada": "F#",
        "VII Disminuida": "Gbb",
        "VII Menor": "Gb",
        "VII Mayor": "G",
        "VII Aumentada":"G#"
    },
    "A": {
        "I Justa": "A",
        "I Aumentada": "A#",
        "II Disminuida": "Bbb",
        "II Menor": "Bb",
        "II Mayor": "B",
        "II Aumentada": "B#",
        "III Disminuida": "Cb",
        "III Menor": "C",
        "III Mayor": "C#",
        "III Aumentada": "Cx",
        "IV Disminuida": "Db",
        "IV Justa": "D",
        "IV Aumentada": "D#",
        "V Disminuida": "Eb",
        "V Justa": "E",
        "V Aumentada": "E#",
        "VI Disminuida": "Fb",
        "VI Menor": "F",
        "VI Mayor": "F#",
        "VI Aumentada": "Fx",
        "VII Disminuida": "Gb",
        "VII Menor": "G",
        "VII Mayor": "G#",
        "VII Aumentada":"Gx"
    },
    "A#": {
        "I Justa": "A#",
        "I Aumentada": "Ax",
        "II Disminuida": "Bb",
        "II Menor": "B",
        "II Mayor": "B#",
        "II Aumentada": "Bx",
        "III Disminuida": "C",
        "III Menor": "C#",
        "III Mayor": "Cx",
        "III Aumentada": "None",
        "IV Disminuida": "D",
        "IV Justa": "D#",
        "IV Aumentada": "Dx",
        "V Disminuida": "E",
        "V Justa": "E#",
        "V Aumentada": "Ex",
        "VI Disminuida": "F",
        "VI Menor": "F#",
        "VI Mayor": "Fx",
        "VI Aumentada": "None",
        "VII Disminuida": "G",
        "VII Menor": "G#",
        "VII Mayor": "Gx",
        "VII Aumentada":"None"
    },
    "Ax": {
        "I Justa": "Ax",
        "I Aumentada": "None",
        "II Disminuida": "B",
        "II Menor": "B#",
        "II Mayor": "Bx",
        "II Aumentada": "None",
        "III Disminuida": "C#",
        "III Menor": "Cx",
        "III Mayor": "None",
        "III Aumentada": "None",
        "IV Disminuida": "D#",
        "IV Justa": "Dx",
        "IV Aumentada": "None",
        "V Disminuida": "E#",
        "V Justa": "Ex",
        "V Aumentada": "None",
        "VI Disminuida": "F#",
        "VI Menor": "Fx",
        "VI Mayor": "None",
        "VI Aumentada": "None",
        "VII Disminuida": "G#",
        "VII Menor": "Gx",
        "VII Mayor": "None",
        "VII Aumentada":"None"
    },
    "Bbb": {
        "I Justa": "Bbb",
        "I Aumentada": "Bb",
        "II Disminuida": "None",
        "II Menor": "Cbb",
        "II Mayor": "Cb",
        "II Aumentada": "C",
        "III Disminuida": "None",
        "III Menor": "Dbb",
        "III Mayor": "Db",
        "III Aumentada": "D",
        "IV Disminuida": "None",
        "IV Justa": "Ebb",
        "IV Aumentada": "Eb",
        "V Disminuida": "Fbb",
        "V Justa": "Fb",
        "V Aumentada": "F",
        "VI Disminuida": "None",
        "VI Menor": "Gbb",
        "VI Mayor": "Gb",
        "VI Aumentada": "G",
        "VII Disminuida": "None",
        "VII Menor": "Abb",
        "VII Mayor": "Ab",
        "VII Aumentada":"A"
    },
    "Bb": {
        "I Justa": "Bb",
        "I Aumentada": "B",
        "II Disminuida": "Cbb",
        "II Menor": "Cb",
        "II Mayor": "C",
        "II Aumentada": "C#",
        "III Disminuida": "Dbb",
        "III Menor": "Db",
        "III Mayor": "D",
        "III Aumentada": "D#",
        "IV Disminuida": "Ebb",
        "IV Justa": "Eb",
        "IV Aumentada": "E",
        "V Disminuida": "Fb",
        "V Justa": "F",
        "V Aumentada": "F#",
        "VI Disminuida": "Gbb",
        "VI Menor": "Gb",
        "VI Mayor": "G",
        "VI Aumentada": "G#",
        "VII Disminuida": "Abb",
        "VII Menor": "Ab",
        "VII Mayor": "A",
        "VII Aumentada":"A#"
    },
    "B": {
        "I Justa": "B",
        "I Aumentada": "B#",
        "II Disminuida": "Cb",
        "II Menor": "C",
        "II Mayor": "C#",
        "II Aumentada": "Cx",
        "III Disminuida": "Db",
        "III Menor": "D",
        "III Mayor": "D#",
        "III Aumentada": "Dx",
        "IV Disminuida": "Eb",
        "IV Justa": "E",
        "IV Aumentada": "E#",
        "V Disminuida": "F",
        "V Justa": "F#",
        "V Aumentada": "Fx",
        "VI Disminuida": "Gb",
        "VI Menor": "G",
        "VI Mayor": "G#",
        "VI Aumentada": "Gx",
        "VII Disminuida": "Ab",
        "VII Menor": "A",
        "VII Mayor": "A#",
        "VII Aumentada":"Ax"
    },
    "B#": {
        "I Justa": "B#",
        "I Aumentada": "Bx",
        "II Disminuida": "C",
        "II Menor": "C#",
        "II Mayor": "Cx",
        "II Aumentada": "None",
        "III Disminuida": "D",
        "III Menor": "D#",
        "III Mayor": "Dx",
        "III Aumentada": "None",
        "IV Disminuida": "E",
        "IV Justa": "E#",
        "IV Aumentada": "Ex",
        "V Disminuida": "F#",
        "V Justa": "Fx",
        "V Aumentada": "None",
        "VI Disminuida": "G",
        "VI Menor": "G#",
        "VI Mayor": "Gx",
        "VI Aumentada": "None",
        "VII Disminuida": "A",
        "VII Menor": "A#",
        "VII Mayor": "Ax",
        "VII Aumentada":"None"
    },
    "Bx": {
        "I Justa": "Bx",
        "I Aumentada": "None",
        "II Disminuida": "C#",
        "II Menor": "Cx",
        "II Mayor": "None",
        "II Aumentada": "None",
        "III Disminuida": "D#",
        "III Menor": "Dx",
        "III Mayor": "None",
        "III Aumentada": "None",
        "IV Disminuida": "E#",
        "IV Justa": "Ex",
        "IV Aumentada": "None",
        "V Disminuida": "Fx",
        "V Justa": "None",
        "V Aumentada": "None",
        "VI Disminuida": "G#",
        "VI Menor": "Gx",
        "VI Mayor": "None",
        "VI Aumentada": "None",
        "VII Disminuida": "A#",
        "VII Menor": "Ax",
        "VII Mayor": "None",
        "VII Aumentada":"None"
    },
}

# Selección de Modos
def EsentIA():
    # Presentación y Selección de Modos de la IA
    print("¡Bienvenido a E-Sent-IA!, el asistente qué cualquier compositor desea tener, ¿En qué puedo ayudarte?")
    while True:
        Modo = input("Escribe [Modos] para ver los Modos de la IA o Seleccione el Modo: ")
        if Modo == "Modos":
            print("Intervalos (I)")
            print("Acordes (II)")
            print("Escalas y Modos (III)")
            Modo = input("Seleccione el Modo: ")
        if Modo == "I":
            while True:
                NotaBase = input("Nota Base: ")
                TipoIntervalo = input("Tipo de Intervalo: ")
                print(CalculadoraInterválica(NotaBase, TipoIntervalo))
        if Modo == "II":
            # Opciones
            print("Escribe [Mostrar] para ver las diferentes Opciones o [Salir] para cambiar de Modo")
            while True:
                # Entrada I: Nota Base
                NotaBase = input("Nota Base: ")
                # Mostrar Nota Base
                while NotaBase == "Mostrar":
                    Disponibles = list(Intervalos.keys())
                    print(Disponibles)
                    NotaBase = input("Nota Base: ")
                    if NotaBase is Disponibles:
                        break
                    elif NotaBase is not Disponibles:
                        continue
                # Salir Nota Base
                if NotaBase == "Salir":
                    Salir = input("Desea Salir del Modo Intervalos? (Sí/No): ").lower()
                    if Salir == "si":
                        break
                    elif Salir == "no" or Salir is None:
                        continue
                # Entrada II: Tipo de Acorde
                TipoAcorde = input("Tipo de Acorde: ")
                # Mostrar Tipo de Acorde
                while TipoAcorde == "Mostrar":
                    Disponibles = list(GeneradorAcordes[NotaBase][TipoAcorde].keys())
                    print(Disponibles)
                    TipoAcorde = input("Tipo de Acorde: ")
                    if TipoAcorde is Disponibles:
                        break
                    elif TipoAcorde is not Disponibles:
                        continue
                # Salir Tipo de Acorde
                if TipoAcorde == "Salir":
                    Salir = input("Desea Salir del Modo Intervalos? (Sí/No): ").lower()
                    if Salir == "si":
                        break
                    elif Salir == "no" or Salir is None:
                        continue
                print(f"{NotaBase}{TipoAcorde} está formado por: {GeneradorAcordes(NotaBase, TipoAcorde)}")

# Modo I: Intervalos
def CalculadoraInterválica(NotaBase, TipoIntervalo):
    if NotaBase in Intervalos and TipoIntervalo in Intervalos[NotaBase]:
        Resultado = Intervalos[NotaBase][TipoIntervalo]
        return Resultado
def GeneradorAcordes(NotaBase, TipoAcorde):
    # Diccionario de Acordes
    Acordes = {
        # Acordes Triada:
        "M": {
            "Notas": [
                Intervalos[NotaBase]["I Justa"],
                Intervalos[NotaBase]["III Mayor"],
                Intervalos[NotaBase]["V Justa"]
            ]
        },
        "M(b5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["III Mayor"],
            Intervalos[NotaBase]["V Disminuida"]
        },
        "Aug": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["III Mayor"],
            Intervalos[NotaBase]["V Aumentada"]
        },
        "m": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["III Menor"],
            Intervalos[NotaBase]["V Justa"]
        },
        "Dim": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["III Menor"],
            Intervalos[NotaBase]["V Disminuida"]
        },
        "m(#5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["III Menor"],
            Intervalos[NotaBase]["V Aumentada"]
        },
        "Sus2": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["II Mayor"],
            Intervalos[NotaBase]["V Justa"]
        },
        "Sus2(b5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["II Mayor"],
            Intervalos[NotaBase]["V Disminuida"]
        },
        "Sus2(#5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["II Mayor"],
            Intervalos[NotaBase]["V Aumentada"]
        },
        "Sus4": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["IV Justa"],
            Intervalos[NotaBase]["V Justa"]
        },
        "Sus4(b5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["IV Justa"],
            Intervalos[NotaBase]["V Disminuida"]
        },
        "Sus4(#5)": {
            Intervalos[NotaBase]["I Justa"],
            Intervalos[NotaBase]["IV Justa"],
            Intervalos[NotaBase]["V Aumentada"]
        },
        # Acordes con 6ª
        "6": {
            "Notas": [
                Intervalos[NotaBase]["I Justa"],
                Intervalos[NotaBase]["III Mayor"],
                Intervalos[NotaBase]["V Justa"],
                Intervalos[NotaBase]["VI Mayor"]
            ]
        },
        # Acordes con 7ª
        "M7": {
            "Notas": [
                Intervalos[NotaBase]["I Justa"],
                Intervalos[NotaBase]["III Mayor"],
                Intervalos[NotaBase]["V Justa"],
                Intervalos[NotaBase]["VII Mayor"]
            ]
        },
    }
    # Función
    if NotaBase in Intervalos and TipoAcorde in Acordes:
        Resultado = Acordes[TipoAcorde]["Notas"]
        return Resultado
EsentIA()